# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library

In [122]:
import numpy as np

In [123]:
#3.2: create a random 10x10 array named A

In [124]:
A = np.random.rand(5,5)
A

array([[0.09543929, 0.82178333, 0.82561193, 0.49984949, 0.31082127],
       [0.32197879, 0.18079175, 0.13091039, 0.35686214, 0.221893  ],
       [0.47074758, 0.05613   , 0.00141736, 0.34475858, 0.43411337],
       [0.17140333, 0.31093195, 0.96612744, 0.20821836, 0.48449493],
       [0.24822932, 0.23445671, 0.37778287, 0.13055619, 0.72401538]])

In [125]:
#3.3: return only the odd rows of A

In [126]:
odd_rows_A = A[::2]
odd_rows_A

array([[0.09543929, 0.82178333, 0.82561193, 0.49984949, 0.31082127],
       [0.47074758, 0.05613   , 0.00141736, 0.34475858, 0.43411337],
       [0.24822932, 0.23445671, 0.37778287, 0.13055619, 0.72401538]])

In [127]:
#3.4: perform a matrix multiplication of A with it's transposed
A.T

array([[0.09543929, 0.32197879, 0.47074758, 0.17140333, 0.24822932],
       [0.82178333, 0.18079175, 0.05613   , 0.31093195, 0.23445671],
       [0.82561193, 0.13091039, 0.00141736, 0.96612744, 0.37778287],
       [0.49984949, 0.35686214, 0.34475858, 0.20821836, 0.13055619],
       [0.31082127, 0.221893  , 0.43411337, 0.48449493, 0.72401538]])

In [128]:
A_AT = A*A.T
A_AT

array([[9.10865839e-03, 2.64596804e-01, 3.88654813e-01, 8.56758653e-02,
        7.71549523e-02],
       [2.64596804e-01, 3.26856583e-02, 7.34800017e-03, 1.10959842e-01,
        5.20243049e-02],
       [3.88654813e-01, 7.34800017e-03, 2.00890532e-06, 3.33080728e-01,
        1.64000592e-01],
       [8.56758653e-02, 1.10959842e-01, 3.33080728e-01, 4.33548865e-02,
        6.32538129e-02],
       [7.71549523e-02, 5.20243049e-02, 1.64000592e-01, 6.32538129e-02,
        5.24198272e-01]])

In [129]:
#3.5: compute the matrix inverse of A
B = np.copy(A)
A_Inv = np.linalg.inv(A)
A_Inv

array([[  78.48012838, -339.37707079,  264.77115522,   17.75906163,
        -100.31937078],
       [  48.45115646, -202.51037797,  156.22845523,    8.53276757,
         -58.11887114],
       [   2.11319126,  -10.79180436,    8.27924854,    2.27801378,
          -4.08833505],
       [ -77.66623723,  336.68230304, -259.59345474,  -16.82498262,
          97.06627679],
       [ -29.69451751,  126.85401496,  -98.87773422,   -7.00658239,
          39.22633322]])

In [130]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [131]:
indices = np.where(A>0.5)
print(A)
for n in range(indices[0][0:].size):
    A[indices[0][n],indices[1][n]] = A[indices[0][n],indices[1][n]]/2
print(indices)    
print(A)


[[0.09543929 0.82178333 0.82561193 0.49984949 0.31082127]
 [0.32197879 0.18079175 0.13091039 0.35686214 0.221893  ]
 [0.47074758 0.05613    0.00141736 0.34475858 0.43411337]
 [0.17140333 0.31093195 0.96612744 0.20821836 0.48449493]
 [0.24822932 0.23445671 0.37778287 0.13055619 0.72401538]]
(array([0, 0, 3, 4], dtype=int64), array([1, 2, 2, 4], dtype=int64))
[[0.09543929 0.41089166 0.41280596 0.49984949 0.31082127]
 [0.32197879 0.18079175 0.13091039 0.35686214 0.221893  ]
 [0.47074758 0.05613    0.00141736 0.34475858 0.43411337]
 [0.17140333 0.31093195 0.48306372 0.20821836 0.48449493]
 [0.24822932 0.23445671 0.37778287 0.13055619 0.36200769]]
